name: Deploy to DO Autoscale Pool

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Get public IPv4s for droplets
        id: droplets
        run: |
          IPS=$(doctl compute droplet list \
            --tag-name "${{ secrets.DROPLET_TAG }}" \
            --no-header \
            --format PublicIPv4 | tr '\n' ',' | sed 's/,$//')
          echo "IPS=$IPS" >> $GITHUB_OUTPUT

      - name: Debug Droplet IPs
        run: echo "Droplets:" ${{ steps.droplets.outputs.IPS }}

      - name: Install droplet SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}
          known_hosts: '*'

      - name: Deploy incrementally to droplets
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ steps.droplets.outputs.IPS }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}
          script: |
            set -e

            DEPLOY_PATH="/var/www/html/variety/wp-content/themes/variety"

            mkdir -p $(dirname "$DEPLOY_PATH")

            # Setup GitHub deploy key for cloning
            mkdir -p /root/.ssh
            echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > /root/.ssh/id_rsa
            chmod 600 /root/.ssh/id_rsa
            ssh-keyscan -H github.com >> /root/.ssh/known_hosts

            if [ -d "$DEPLOY_PATH/.git" ]; then
              cd "$DEPLOY_PATH"
              git config pull.rebase false   # merge instead of rebase
              git pull origin main
            else
              git clone git@github.com:EM-brijesh/variety-prod.git "$DEPLOY_PATH"
            fi

            # Set permissions
            chown -R www-data:www-data "$DEPLOY_PATH" || true

            # Restart services
            systemctl restart php8.2-fpm || true
            systemctl restart nginx || true
