name: Deploy to DO Autoscale Pool

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/latest/download/doctl-$(uname -s)-amd64.tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin

      - name: Authenticate doctl
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          doctl auth init -t "$DO_API_TOKEN"

      - name: Get public IPv4s for droplets with tag
        id: droplets
        run: |
          IPS=$(doctl compute droplet list --tag-name "${{ secrets.DROPLET_TAG }}" --no-header --format PublicIPv4 | tr '\n' ',' | sed 's/,$//')
          echo "IPS=$IPS" >> $GITHUB_OUTPUT

      - name: Install SSH key for actions (so appleboy can use it)
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}
          known_hosts: 'github.com' # placeholder; appleboy can work without this but shimataro helps set the key

      - name: Deploy to droplets (SSH & git pull)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ steps.droplets.outputs.IPS }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}
          script: |
            set -e
            # ensure repo exists and is the right branch
            if [ -d /var/www/html/actions .git ]; then
              cd /var/www/html/actions
              git fetch --all
              git reset --hard origin/main
            else
              git clone [email protected]:EM-brijesh/variety-prod.git /var/www/html/actions
            fi
            chown -R www-data:www-data /var/www/html/actions || true
            # restart services
            systemctl restart php8.2-fpm || true
            systemctl restart nginx || true
