name: Deploy to DO Autoscale Pool

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install doctl
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      # Get droplets by tag
      - name: Get public IPv4s for droplets with tag
        id: droplets
        run: |
          IPS=$(doctl compute droplet list \
            --tag-name "${{ secrets.DROPLET_TAG }}" \
            --no-header \
            --format PublicIPv4 | tr '\n' ',' | sed 's/,$//')
          echo "IPS=$IPS" >> $GITHUB_OUTPUT

      # Debug step to print IPs
      - name: Debug Droplet IPs
        run: |
          echo "Droplets: ${{ steps.droplets.outputs.IPS }}"

      # Load SSH key
      - name: Install SSH key for Actions
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}
          known_hosts: ''

      # Deploy via SSH
      - name: Deploy to droplets
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ steps.droplets.outputs.IPS }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}
          script: |
            set -e
            if [ -d /var/www/html/.git ]; then
              cd /var/www/html
              git fetch --all
              git reset --hard origin/main
            else
              rm -rf /var/www/html
              git clone [email protected]:EM-brijesh/variety-prod.git /var/www/html
            fi
            chown -R www-data:www-data /var/www/html || true
            systemctl restart php8.2-fpm || true
            systemctl restart nginx || true
