name: Deploy to DO Autoscale Pool

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code locally (optional)
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Install doctl
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      # 3️⃣ Get droplets by tag
      - name: Get public IPv4s for droplets
        id: droplets
        run: |
          IPS=$(doctl compute droplet list \
            --tag-name "${{ secrets.DROPLET_TAG }}" \
            --no-header \
            --format PublicIPv4 | tr '\n' ',' | sed 's/,$//')
          echo "IPS=$IPS" >> $GITHUB_OUTPUT

      # 4️⃣ Debug droplet IPs
      - name: Debug Droplet IPs
        run: |
          echo "Droplets: ${{ steps.droplets.outputs.IPS }}"

      # 5️⃣ Load SSH key for droplet access
      - name: Install droplet SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}
          known_hosts: '*'

      # 6️⃣ Deploy code incrementally to droplets
      - name: Deploy to droplets
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ steps.droplets.outputs.IPS }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}
          script: |
            set -e

            DEPLOY_PATH="/var/www/html/variety/wp-content/themes/variety"

            # Prepare GitHub deploy key for cloning
            mkdir -p /root/.ssh
            echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > /root/.ssh/id_rsa
            chmod 600 /root/.ssh/id_rsa
            ssh-keyscan -H github.com >> /root/.ssh/known_hosts

            # Incremental deploy
            if [ -d "$DEPLOY_PATH/.git" ]; then
            echo "Block 1"
              cd "$DEPLOY_PATH"
              echo "Block 2"
              pwd
              git status
              git config pull.rebase false
              git pull origin main
            else
              if [ -d "$DEPLOY_PATH" ]; then
                echo "Backing up existing folder..."
                mv "$DEPLOY_PATH" "${DEPLOY_PATH}_backup_$(date +%s)"
              fi
              git clone git@github.com:EM-brijesh/variety-prod.git "$DEPLOY_PATH"
            fi

            # Set permissions
            chown -R www-data:www-data "$DEPLOY_PATH" || true

            # Restart services
            systemctl restart php8.4-fpm || true
            systemctl restart nginx || true
